FROM ubuntu:latest

MAINTAINER Michael Thon <mike.thon@gmail.com>

RUN apt-get update
RUN apt-get install -y emboss python wget unzip
RUN wget https://github.com/mthon/mikes-tools/archive/master.zip
RUN unzip master.zip

